WIP: migrate s3link features
halo-sigs/plugin-s3 pull request #59
Opened 2023-08-06 03:32 UTC by longjuan

2023-08-06 14:34 UTC, ruibaby requested changes

2023-08-06 14:34 UTC, ruibaby commented on console/src/components/AttachmentFileTypeIcon.vue
> +<script lang="ts" setup>
这个组件如果在这里有用到的话，似乎后续可以在 Console 全局注册一下。

2023-08-06 14:34 UTC, ruibaby commented on console/src/components/filter/FilterCleanButton.vue
> +<script lang="ts" setup>
这个组件已经在 Console 全局注册，可参考：https://github.com/halo-dev/halo/pull/4182/files#diff-0c7a02cd6ea10eb7eb097ef5423854bf69859d2941dd81e4f67d0bb7f808da78

2023-08-06 14:34 UTC, ruibaby commented on console/src/components/filter/FilterTag.vue
> +<script lang="ts" setup>
在 2.8 已经修改了条件过滤的组件并全局注册，可以查看：https://github.com/halo-dev/halo/pull/4182

2023-08-06 14:39 UTC, longjuan commented on console/src/components/filter/FilterCleanButton.vue
> +<script lang="ts" setup>
已经用了新的，忘了删旧的

2023-08-06 14:39 UTC, longjuan commented on console/src/components/filter/FilterTag.vue
> +<script lang="ts" setup>
已经用了新的，忘了删旧的

2023-08-06 14:40 UTC, longjuan commented on console/src/components/filter/FilterTag.vue
> +<script lang="ts" setup>
好像没用全局的

2023-08-06 14:44 UTC, longjuan commented on console/src/components/filter/FilterTag.vue
> +<script lang="ts" setup>
已经用新的了，这个忘删了

2023-09-04 04:35 UTC, longjuan commented
> 目前待优化的功能：
> 
> * [ ]  列出未关联的文件时会查询多次数据库，期望优化成只查询一次，但是代码改动较大。
> * [ ]  关联文件时没有查询是否已在附件库（防止多次操作），需要改动成对于一整个关联请求查询一次数据库。

/ping @halo-sigs/halo 看这两个优化点可不可以后面再做，反正现在能用。

2023-09-06 07:45 UTC, JohnNiang commented
/ping @halo-sigs/halo

2023-09-07 15:18 UTC, longjuan commented
![image](https://github.com/halo-sigs/plugin-s3/assets/28662535/cf74aec9-8957-456f-9514-fe03fcfc598c)
已实现双标签页操作也不会重复关联

2023-09-07 15:22 UTC, ruibaby commented
> 

我觉得 OK。

cc @halo-sigs/halo

2023-09-11 16:04 UTC, merged